bakalarka_ikaros:
    resource: "@BakalarkaIkarosBundle/Controller/"
    type:     annotation
    prefix:   /
    
login:
  pattern: /login
  defaults: { _controller: BakalarkaIkarosBundle:Login:login }

login_check:
  pattern: /login_check
  
logout:
  pattern: /logout 
  
home:
  pattern: /home   
  defaults: { _controller: BakalarkaIkarosBundle:Default:index }

norma:
  pattern: /norma
  defaults: { _controller: BakalarkaIkarosBundle:Default:norma }
  
register:
  pattern: /register   
  defaults: { _controller: BakalarkaIkarosBundle:Register:register }

allSystems:
  pattern: /allSystems
  defaults: { _controller: BakalarkaIkarosBundle:Systems:allSystems }

mySystems:
  pattern: /mySystems
  defaults: { _controller: BakalarkaIkarosBundle:Systems:mySystems }

detail:
  pattern: /detail/{id}
  defaults: { _controller: BakalarkaIkarosBundle:Systems:detail }

detailAdmin:
  pattern: /detailA/{id}
  defaults: { _controller: BakalarkaIkarosBundle:Systems:detailAdmin }

detailPart:
  pattern: /detailPart/{id}
  defaults: { _controller: BakalarkaIkarosBundle:Parts:detailPart }

detailPCB:
  pattern: /detailPCB/{id}
  defaults: { _controller: BakalarkaIkarosBundle:PCB:detailPCB }

editPCB:
  pattern: /editPCB/{id}
  defaults: { _controller: BakalarkaIkarosBundle:PCB:editPCB }

delSystem:
  pattern: /delSystem/{id}
  defaults: { _controller: BakalarkaIkarosBundle:Systems:delSystem }

delDesk:
  pattern: /delDesk/{id}
  defaults: { _controller: BakalarkaIkarosBundle:PCB:delDesk }

delDeskAjax:
  pattern: /delDesk
  defaults: { _controller: BakalarkaIkarosBundle:PCB:delDeskAjax }

delSMT:
  pattern: /delSMT/{id}
  defaults: { _controller: BakalarkaIkarosBundle:PCB:delSMT, id:-1  }

delPartID:
  pattern: /delPart/{id}
  defaults: { _controller: BakalarkaIkarosBundle:Parts:delPartID }

delPart:
  pattern: /delPart
  defaults: { _controller: BakalarkaIkarosBundle:Parts:delPart }

editPart:
  pattern: /editPart/{id}
  defaults: { _controller: BakalarkaIkarosBundle:Parts:editPart }

newSystem:
    pattern: /newSystem
    defaults: { _controller: BakalarkaIkarosBundle:Systems:newSystem }

detailSystem:
    pattern: /detailSystem/{id}
    defaults: { _controller: BakalarkaIkarosBundle:Systems:detailSystem }

editSystem:
    pattern: /editSystem/{id}
    defaults: { _controller: BakalarkaIkarosBundle:Systems:editSystem }

newPCB:
    pattern: /newPCB/{id}
    defaults: { _controller: BakalarkaIkarosBundle:PCB:newPCB, id:-1 }

newPart:
    pattern: /newPart/{id}
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newPart }

newResistorAjax:
    pattern: /newResistor
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newResistorAjax }

newCapacitor:
    pattern: /newCapacitor
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newCapacitor}

newFuse:
    pattern: /newFuse
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newFuse}

newConnection:
    pattern: /newConnection
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newConnection}

newConSoc:
    pattern: /newConSoc
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newConSoc}

newConGen:
    pattern: /newConGen
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newConGen}

newSwitch:
    pattern: /newSwitch
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newSwitch}

newFilter:
    pattern: /newFilter
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newFilter}

newRotElaps:
    pattern: /newRotElaps
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newRotElaps}

newTubeWave:
    pattern: /newTubeWave
    defaults: { _controller: BakalarkaIkarosBundle:Parts:newTubeWave}

newPCBAjax:
    pattern: /newPCBA
    defaults: { _controller: BakalarkaIkarosBundle:PCB:newPCBAjax }


  


# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
