bakalarka_ikaros:
    resource: "@BakalarkaIkarosBundle/Resources/config/routing.yml"
    prefix:   /

ikaros:
    resource: "@BakalarkaIkarosBundle/Controller"
    type:     annotation

login_check:
  pattern: /login_check

logout:
  pattern: /logout