security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Bakalarka\IkarosBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: Bakalarka\IkarosBundle\Entity\User, property: Username }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            form_login: 
              login_path:  login                 
              check_path:  login_check
              default_target_path: /mySystems
            logout:
                path:   /logout
                target: /home
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"    

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/allSystems, roles: ROLE_ADMIN }
        - { path: ^/detailA, roles: ROLE_ADMIN }
        - { path: ^/mySystems, roles: ROLE_USER }
        - { path: ^/newSystem, roles: ROLE_USER }
        - { path: ^/newPCB, roles: ROLE_USER }
        - { path: ^/newPart, roles: ROLE_USER }
        - { path: ^/delSystem, roles: ROLE_USER }
        - { path: ^/delDesk, roles: ROLE_USER }
        - { path: ^/delPart, roles: ROLE_USER }
        - { path: ^/detail, roles: ROLE_USER }